version: '3.6'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus.yml/:/etc/prometheus/prometheus.yml
    - ./alert.rules/:/etc/prometheus/alert.rules
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - 9090:9090

  alertmanager:
    image: prom/alertmanager
    user: root
    ports:
      - 127.0.0.1:9093:9093
    volumes:
      - ./config.yml/:/etc/alertmanager/config.yml
    container_name: alertmanager
    hostname: alertmanager
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'

  grafana:
    image: grafana/grafana:latest
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

